apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: us-docker.pkg.dev/project1-428321/hello-world/cicd-app
        # - name: tobi-server
        #   image: 343494696876.dkr.ecr.us-east-1.amazonaws.com/tobi-server
