apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: cicd-app
  ports:
    - name: other
      protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
